version: 2
jobs:
  build:
    docker:
      - image: circleci/node:current

    working_directory: ~/webnetik-api

    steps:
      - checkout
  deploy:
    machine:
        enabled: true
    steps:
      - run:
          name: Deploy Over SSH
          command: |
            ssh $DROPLET_USER@$DROPLET_IP "bash /var/www/deploy_api_project.sh"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master