const config = {
    GET_USERS: 'GET_USERS',
    ADD_NEW_USER: 'ADD_NEW_USER',
    GET_ROLES: 'GET_ROLES',
    ADD_NEW_ROLE: 'ADD_NEW_ROLE',
    GET_CAPABILITIES: 'GET_CAPABILITIES',
    CHANGE_ROLE_CAPABILITIES: 'CHANGE_ROLE_CAPABILITIES',
    DELETE_IMAGE: 'DELETE_IMAGE'
};

module.exports = config;